{% extends 'layout.swig' %}

{% block content %}
<div class="row stacked-content">
<div class="col-md-10 col-md-offset-1">
<a href="http://github.com/ccarlile"><p>I've got a Github</p></a>

<a href="http://github.com/resume/raw/master/resume.pdf"><p>My CV is on there</p></a>

<p>
<a href="http://facebook.com/flylikeabanana">Also I have a Facebook</a>
</p>

<p>christopher dot carlile at gmail dot com</p>

</div>
</div>
{% endblock %}
